### ISSUE TITLE
chore: Add eslint rule import order

### ISSUE THREAD

**Issue by abhishek310001** [jalantechnologies/react-native-template#30]
We need to enforce a consistent import order across the project to improve code readability and maintainability. Specifically, we want to ensure that module imports (e.g., native-base, react) are listed before relative file imports.

**Comment by bbbneo333** [comment]
@abhishek310001 - Let's make sure import order rules are as same as we have in MERN boilerplate - https://github.com/jalantechnologies/boilerplate-mern
